package cn.net.cvtt.imps.lianzi.enums;

import cn.net.cvtt.lian.common.util.EnumInteger;

public enum NotifyType implements EnumInteger {
	CMD_VERSION_CHANGED_NOTIFY(20002),//版本号变更通知
	CMD_BATCH_VERSION_CHANGED_NOTIFY(20003),//批量的版本号变更通知
	
	CMD_IDENTITY_CHANGED_NOTIFY(21001),//联职位变更通知
	CMD_POSITION_CHANGED_NOTIFY(21002),//联岗位变更通知
	CMD_REMOVE_FROM_LIAN_NOTIFY(21003),//被移除联通知
	CMD_REMOVE_FROM_ORG_NOTIFY(21004),//被移除组织通知
	
	CMD_REGISTER_NOTIFY(30001),//注册成功通知（小联报道）
	
	CMD_CREATE_ORG_PASSED_NOTIFY(30101),//创建组织审核通过通知
	CMD_CREATE_ORG_REJECTED_NOTIFY(30102),//创建组织审核未通过通知
	CMD_CREATE_LIAN_AUDIT_NOTIFY(30103),//创建联申请审核通知
	CMD_CREATE_LIAN_PASSED_NOTIFY(30104),//创建联申请审核通过通知
	CMD_CREATE_LIAN_REJECTED_NOTIFY(30105),//创建联申请审核未通过通知
	
	CMD_MEMBER_JOIN_LIAN_NOTIFY(30201),//新用户加入联通知
	CMD_LIAN_MEMBER_REMOVED_NOTIFY(30202),//移除联成员通知
	CMD_ADD_LIAN_COUNCIL_MEMBER_NOTIFY(30203),//任命联委会成员通知
	CMD_REMOVE_LIAN_COUNCIL_MEMBER_NOTIFY(30204),//移除联委会成员通知
	CMD_CHANGE_LIAN_SECRETRY_OLD_NOTIFY(30205),//更换联秘通知-旧联秘
	CMD_CHANGE_LIAN_SECRETRY_NEW_NOTIFY(30206),//更换联秘通知-新联秘
	CMD_CHANGE_LIAN_CHIEF_OLD_NOTIFY(30207),//更换（转让）联长通知-旧联长
	CMD_CHANGE_LIAN_CHIEF_NEW_NOTIFY(30208),//更换（转让）联长通知-新联长
	
	CMD_ORGANIZATION_INVITATION_ORG_LEADER_NOTIFY(30301),//总秘或大联长收到的邀请加入会员联邀请函
	CMD_ORGANIZATION_INVITATION_REJECTED_LIAN_LEADER_NOTIFY(30302),//总秘或大联长拒绝邀请，给会员联联秘或联长发的通知
	CMD_JOIN_LIAN_APPLY_ORG_LEADER_NOTIFY(30303),//总秘或大联长收到组织成员申请加入会员联的确认通知
	CMD_JOIN_LIAN_APPLY_LIAN_LEADER_NOTIFY(30304),//会员联联秘或联长收到申请加入会员联的通知
	CMD_JOIN_LIAN_APPLY_REJECTED_ORG_LEADER_NOTIFY(30305),//申请加入会员联申请被拒绝， 总秘或大联长收到被拒绝通知
	CMD_JOIN_LIAN_APPLY_PASSED_ORG_LEADER_NOTIFY(30306),//申请加入会员联申请通过， 总秘或大联长收到通过通知
	CMD_JOIN_LIAN_APPLY_REJECTED_APPLICANT_NOTIFY(30307),//申请加入会员联申请被拒绝， 申请者收到被拒绝通知
	CMD_IDENTITY_DEFINE_ORG_LEADER_NOTIFY(30308),//总秘或大联长收到的会员身份设定的确认函
	CMD_IDENTITY_DEFINE_PASSED_LIAN_LEADER_NOTIFY(30309),//总秘或大联长通过确认，给会员联联秘或联长发的通知
	CMD_IDENTITY_DEFINE_PASSED_ACCESSUSER_NOTIFY(30310),//总秘或大联长通过确认，给对接人发的通知
	CMD_IDENTITY_DEFINE_REJECTED_LIAN_LEADER_NOTIFY(30311),//总秘或大联长拒绝确认，给会员联联秘或联长发的通知
	CMD_ORG_IDENTITY_APPLY_JOIN_LIAN_ORG_LEADER_PASSED_ACCESSUSER_NOTIFY(30312),//组织身份申请加入会员联，总秘或大联长通过确认，给对接人发的通知
	CMD_ORG_IDENTITY_APPLY_JOIN_LIAN_ORG_LEADER_REJECTED_ACCESSUSER_NOTIFY(30313),//组织身份申请加入会员联，总秘或大联长拒绝确认，给对接人发的通知
	CMD_IDENTITY_DEFINE_ORG_REGISTERED_LIAN_LEADER_NOTIFY(30314),//会员联联秘或联长收到未认证的组织上线通知
	CMD_PERSON_INVITE_USER_NOTIFY(30315),//用户收到的邀请加入会员联的通知
	CMD_PERSON_INVITE_REJECTED_LIAN_LEADER_NOTIFY(30316),//用户拒绝加入会员联的邀请后，给会员联联秘和联长发的通知
	
	/**
	 * 新任联网站联秘
	 */
	CMD_NET_ASSUME_NET_SECRETRY(30601),
	/**
	 * 卸任联网站联秘
	 */
	CMD_NET_OUTGOING_NET_SECRETRY(30602),
	/**
	 * 新任联网站编辑人
	 */
	CMD_NET_ASSUME_NET_EDITOR(30603),
	/**
	 * 联网站编辑内容提交待审批
	 */
	CMD_NET_PENDING_APPROVAL(30604),
	/**
	 * 联网站编辑内容审批未通过
	 */
	CMD_NET_APPROVAL_FAILED(30605),
	
	/**
	 * 未读通知
	 */
	CMD_APPS_NOTICE_UNREADNOTICE_ACTION(31001),
	/**
	 * 紧急通知
	 */
	CMD_APPS_NOTICE_URGENTNOTICE_ACTION(31002),
	
	CMD_NET_LIANNET_NOTIFY(36001),//联网站内容推送
	CMD_NET_VIPLIAN_BROADCAST_NOTIFY(36002),//会员联报内容推送
	CMD_NET_UPSTREAM_BROADCAST_NOTIFY(36003),//上游联报内容推送
	CMD_NET_PEER_BROADCAST_NOTIFY(36004),//同行业联报内容推送
	CMD_NET_DOWNSTREAM_BROADCAST_NOTIFY(36005),//下游行业联报内容推送
	
	
	
	CMD_GROUP_CHAT_TIP_NOTIFY(40000),
	;

	private int intValue;

	private NotifyType(int intValue) {
		this.intValue = intValue;
	}

	@Override
	public int intValue() {
		return this.intValue;
	}

}
